In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
print(np.__version__)

1.19.2

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:    4.7s finished

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test_) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032717,0.001933,0.005183,0.000747,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.727273,0.777778,0.790698,0.900000,0.864865,0.812123,0.062197,10
1,0.271873,0.006135,0.017753,0.002221,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,1
2,0.030918,0.001546,0.003792,0.000747,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.709677,0.705882,0.780488,0.900000,0.864865,0.792182,0.079119,12
3,0.267485,0.006161,0.021742,0.006321,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.764706,0.777778,0.809524,0.900000,0.923077,0.835017,0.064571,7
4,0.030120,0.001162,0.004588,0.001197,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.687500,0.810811,0.790698,0.894737,0.894737,0.815696,0.076913,9
5,0.273868,0.001954,0.019149,0.001466,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.789474,0.809524,0.900000,0.923077,0.844415,0.055653,4
6,0.028519,0.002242,0.004189,0.000399,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.787879,0.810811,0.809524,0.842105,0.888889,0.827842,0.035079,8
7,0.272871,0.004117,0.017353,0.000489,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.764706,0.820513,0.809524,0.900000,0.923077,0.843564,0.059019,5
8,0.030520,0.001619,0.004190,0.000744,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.687500,0.842105,0.780488,0.871795,0.823529,0.801083,0.064050,11
9,0.268881,0.003711,0.017553,0.001017,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.764706,0.871795,0.809524,0.900000,0.923077,0.853820,0.058576,3
10,0.027925,0.000631,0.003790,0.000399,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.823529,0.833333,0.809524,0.900000,0.923077,0.857893,0.045046,2
11,0.214227,0.011517,0.010771,0.001716,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.727273,0.842105,0.809524,0.900000,0.923077,0.840396,0.069486,6

In [17]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9183922682195829

In [18]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[78  7]
 [ 4 45]]

In [19]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.93        85
           1       0.87      0.92      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134

In [20]:
table_pr=pd.DataFrame()

In [21]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]

In [22]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [28]:
table_pr = X_test.copy()

table_pr['Actual'] = y_test
table_pr['Predicted'] = grid_predictions

In [29]:
table_pr.head(134)

     Age  EstimatedSalary  Gender_Male  Actual  Predicted
132   30            87000            1       0          0
309   38            50000            0       0          0
341   35            75000            1       0          0
196   30            79000            0       0          0
246   35            50000            0       0          0
..   ...              ...          ...     ...        ...
168   29           148000            1       1          1
150   26            15000            0       0          0
393   60            42000            1       1          1
66    24            19000            1       0          0
240   42           149000            1       1          1

[134 rows x 5 columns]

In [30]:
table_pr.to_csv("cm.csv",index=False)

In [32]:
#dataset['']



#dataset['Predicted'] = grid_predictions

In [33]:
age_input=float(input("Age:"))
estimatedsalary_input=float(input("Estimated Salary:"))
#children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
#smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:35
Estimated Salary:20000
Sex Male 0 or 1:1

In [34]:
Future_Prediction=grid.predict([[age_input,estimatedsalary_input,sex_male_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]